# Generated by Django 5.1.7 on 2025-04-08 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_fotografia_data_puclicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_puclicacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
