# Generated by Django 5.1.7 on 2025-04-08 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_alter_fotografia_data_puclicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_puclicacao',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 16, 19, 25, 504096, tzinfo=datetime.timezone.utc)),
        ),
    ]
