# Generated by Django 5.1.7 on 2025-04-08 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_alter_fotografia_data_puclicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_puclicacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
