# Generated by Django 5.1.7 on 2025-04-08 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_alter_fotografia_data_puclicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='data_puclicacao',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
