# Generated by Django 5.1.7 on 2025-04-08 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_remove_fotografia_data_puclicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
